### ISSUE TITLE
Failed to establish a new connection: [Errno 111] Connection refused

### ISSUE THREAD

**Issue by ewen-lbh** [joowani/python-arango#137]
I installed arangodb on WSL without success and resorted to a windows install. I can access localhost:8259 in my web browser without issues but upon calling `client.db`, I get the following stacktrace:

```python
Traceback (most recent call last):
  File "/home/ewen/.cache/pypoetry/virtualenvs/schoolsyst-api-KMZzagH4-py3.8/lib/python3.8/site-packages/urllib3/connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "/home/ewen/.cache/pypoetry/virtualenvs/schoolsyst-api-KMZzagH4-py3.8/lib/python3.8/site-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/home/ewen/.cache/pypoetry/virtualenvs/schoolsyst-api-KMZzagH4-py3.8/lib/python3.8/site-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ewen/.cache/pypoetry/virtualenvs/schoolsyst-api-KMZzagH4-py3.8/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/home/ewen/.cache/pypoetry/virtualenvs/schoolsyst-api-KMZzagH4-py3.8/lib/python3.8/site-packages/urllib3/connectionpool.py", line 392, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.8/http/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1010, in _send_output
    self.send(msg)
  File "/usr/lib/python3.8/http/client.py", line 950, in send
    self.connect()
  File "/home/ewen/.cache/pypoetry/virtualenvs/schoolsyst-api-KMZzagH4-py3.8/lib/python3.8/site-packages/urllib3/connection.py", line 187, in connect
    conn = self._new_conn()
  File "/home/ewen/.cache/pypoetry/virtualenvs/schoolsyst-api-KMZzagH4-py3.8/lib/python3.8/site-packages/urllib3/connection.py", line 171, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f91e37cebb0>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ewen/.cache/pypoetry/virtualenvs/schoolsyst-api-KMZzagH4-py3.8/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/home/ewen/.cache/pypoetry/virtualenvs/schoolsyst-api-KMZzagH4-py3.8/lib/python3.8/site-packages/urllib3/connectionpool.py", line 726, in urlopen
    retries = retries.increment(
  File "/home/ewen/.cache/pypoetry/virtualenvs/schoolsyst-api-KMZzagH4-py3.8/lib/python3.8/site-packages/urllib3/util/retry.py", line 439, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8259): Max retries exceeded with url: /_db/_system/_api/collection (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f91e37cebb0>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ewen/.cache/pypoetry/virtualenvs/schoolsyst-api-KMZzagH4-py3.8/lib/python3.8/site-packages/arango/client.py", line 117, in db
    connection.ping()
  File "/home/ewen/.cache/pypoetry/virtualenvs/schoolsyst-api-KMZzagH4-py3.8/lib/python3.8/site-packages/arango/connection.py", line 167, in ping
    resp = self._http.send_request(
  File "/home/ewen/.cache/pypoetry/virtualenvs/schoolsyst-api-KMZzagH4-py3.8/lib/python3.8/site-packages/arango/http.py", line 103, in send_request
    response = session.request(
  File "/home/ewen/.cache/pypoetry/virtualenvs/schoolsyst-api-KMZzagH4-py3.8/lib/python3.8/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/ewen/.cache/pypoetry/virtualenvs/schoolsyst-api-KMZzagH4-py3.8/lib/python3.8/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/home/ewen/.cache/pypoetry/virtualenvs/schoolsyst-api-KMZzagH4-py3.8/lib/python3.8/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8259): Max retries exceeded with url: /_db/_system/_api/collection (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f91e37cebb0>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "schoolsyst_api/database.py", line 56, in <module>
    db = initialize()
  File "schoolsyst_api/database.py", line 38, in initialize
    sys_db = client.db(
  File "/home/ewen/.cache/pypoetry/virtualenvs/schoolsyst-api-KMZzagH4-py3.8/lib/python3.8/site-packages/arango/client.py", line 121, in db
    raise ServerConnectionError('bad connection: {}'.format(err))
arango.exceptions.ServerConnectionError: bad connection: HTTPConnectionPool(host='localhost', port=8259): Max retries exceeded with url: /_db/_system/_api/collection (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f91e37cebb0>: Failed to establish a new connection: [Errno 111] Connection refused'))
```

Here's the relevant function definitions:

```python
def create_collection_if_missing(
    database: arango.database.StandardDatabase, collection_name: str
):
    if not database.has_collection(collection_name):
        database.create_collection(collection_name)


def initialize() -> arango.database.StandardDatabase:
    load_dotenv(".env")
    client = ArangoClient(hosts=os.getenv("ARANGO_HOST", "http://localhost:8259"))
    username, password = os.getenv("ARANGO_USERNAME"), os.getenv("ARANGO_PASSWORD")
    sys_db = client.db(
        name="_system",
        username=username,
        password=password,
        verify=True
    )

    if not sys_db.has_database(os.getenv("ARANGO_DB_NAME")):
        sys_db.create_database(os.getenv("ARANGO_DB_NAME"))

    for c in COLLECTIONS:
        create_collection_if_missing(db, c)

    return db
```

`COLLECTIONS` is just a list of `str`s

I checked (via some `print`s) that the environment variables are loaded correctly (and even if they weren't the error would be something like "incorrect username/password")

**Comment by ewen-lbh** [comment]
Nevermind, I had switched two digits on the port number (it's `8529` and not `8259`)
