### ISSUE TITLE
HeaderParsingError exception with batch execution

### ISSUE THREAD

**Issue by wtfuzz** [joowani/python-arango#141]
I'm getting the following exception each time a batch is committed in a `begin_batch_execution` context

```
2020-08-25 09:13:16,766 Failed to parse headers (url=http://127.0.0.1:8529/_db/db/_api/batch): [StartBoundaryNotFoundDefect(), MultipartInvariantViolationDefect()], unparsed data: ''
Traceback (most recent call last):
  File "/home/fuzz/work/env/lib/python3.8/site-packages/urllib3/connectionpool.py", line 446, in _make_request
    assert_header_parsing(httplib_response.msg)
  File "/home/fuzz/work/env/lib/python3.8/site-packages/urllib3/util/response.py", line 71, in assert_header_parsing
    raise HeaderParsingError(defects=defects, unparsed_data=unparsed_data)
urllib3.exceptions.HeaderParsingError: [StartBoundaryNotFoundDefect(), MultipartInvariantViolationDefect()], unparsed data: ''```

**Comment by joowani** [comment]
Hi @wtfuzz,

Would you be able to give me some sample data + code to reproduce the issue? Also what version of ArangoDB and python-arango are you using? Thanks.

**Comment by joowani** [comment]
Closing due to inactivity. Feel free to re-open if you have any more questions. Thanks!
