### ISSUE TITLE
Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1076)

### ISSUE THREAD

**Issue by a523** [joowani/python-arango#145]
```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/yongxin/source_mirrors/venv/lib64/python3.7/site-packages/arango/collection.py", line 1068, in random
    return self._execute(request, response_handler)
  File "/home/yongxin/source_mirrors/venv/lib64/python3.7/site-packages/arango/api.py", line 66, in _execute
    return self._executor.execute(request, response_handler)
  File "/home/yongxin/source_mirrors/venv/lib64/python3.7/site-packages/arango/executor.py", line 81, in execute
    resp = self._conn.send_request(request)
  File "/home/yongxin/source_mirrors/venv/lib64/python3.7/site-packages/arango/connection.py", line 161, in send_request
    auth=self._auth
  File "/home/yongxin/source_mirrors/venv/lib64/python3.7/site-packages/arango/http.py", line 109, in send_request
    auth=auth
  File "/home/yongxin/source_mirrors/venv/lib64/python3.7/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/yongxin/source_mirrors/venv/lib64/python3.7/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/home/yongxin/source_mirrors/venv/lib64/python3.7/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='production-cluster.ossscms.svc', port=8529): Max retries exceeded with url: /_db/oss-graph/_api/simple/any (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1076)')))
```
I had Install CA certificate like [this](https://www.arangodb.com/docs/stable/deployment-kubernetes-tls.html#linux)
And curl the https endpoint，is ok。
But why I use python client is not work？

**Comment by joowani** [comment]
Hi @a523,

It must be because the certificate is self-signed as suggested by the error message.
Refer to this [documentation page](https://python-driver-for-arangodb.readthedocs.io/en/master/http.html) to see how you can disable certificate verification.

**Comment by a523** [comment]
@joowani Thanks, I did it.

**Comment by joowani** [comment]
Awesome. Closing issue.

**Comment by velvia** [comment]
Sorry I'm hitting the same issue and the link to the doc page is not working.   
Also, instead of disabling the cert verification is there a way to fix it?  Thanks.

**Comment by a523** [comment]
@velvia  This is my way: 
```python

from arango import ArangoClient
from arango.http import DefaultHTTPClient
from arango.response import Response

class SSLVerifyClient(DefaultHTTPClient):
    
    def send_request(self,
                     session,
                     method,
                     url,
                     params=None,
                     data=None,
                     headers=None,
                     auth=None):
        """Send an HTTP request.

        :param session: Requests session object.
        :type session: requests.Session
        :param method: HTTP method in lowercase (e.g. "post").
        :type method: str | unicode
        :param url: Request URL.
        :type url: str | unicode
        :param headers: Request headers.
        :type headers: dict
        :param params: URL (query) parameters.
        :type params: dict
        :param data: Request payload.
        :type data: str | unicode | bool | int | list | dict
        :param auth: Username and password.
        :type auth: tuple
        :returns: HTTP response.
        :rtype: arango.response.Response
        """
        response = session.request(
            method=method,
            url=url,
            params=params,
            data=data,
            headers=headers,
            auth=auth,
            verify="Users/.../ca-arangodb.crt",      #  The path of your crt file
            timeout=60 * 15,
        )
        return Response(
            method=response.request.method,
            url=response.url,
            headers=response.headers,
            status_code=response.status_code,
            status_text=response.reason,
            raw_body=response.text,
        )

arango_client = ArangoClient(hosts=ENDPOINT, http_client=SSLVerifyClient())
db = arango_client.db(db_name, username=DB_USER, password=PASSWORD) 
# ...
```
Also, maybe you need to do that:
>
>LinuxPermalink
>To install a CA certificate in Linux, on Ubuntu, run:
>
>sudo cp ca.crt /usr/local/share/ca-certificates/<some-name>.crt
>sudo update-ca-certificates
