### ISSUE TITLE
`Connection reset by peer` when running script, gets stuck in loop, but not when executed line by line.

### ISSUE THREAD

**Issue by lxr900** [joowani/python-arango#166]
Version

I'm trying to bootstrap an arangodb server (run in a docker container) via a script that creates users, dbs and collections.

The script gives no issues when run step by step via `pdb`, but when run from file it always returns the error below.

Any experience with this? The loops are pretty simple and short (it gets stuck on the first loop creating 3 users), any suggestions on what could be causing the connection issue?

___
```python
# db_setup.py
import secrets
# ...
from arango import ArangoClient

# ...

try:
  client = ArangoClient(hosts='http://localhost:8529')
  sys_db = client.db(username='root', password=root_password)

  users = {
    'progress_dev':'',
    'progress_api':'',
    'customer':''
  }

  for u in users:
    pwd = secrets.token_hex(6)
    sys_db.create_user(username=u, password=pwd) # <------- This is the offending line
    users[u] = pwd

# ...
```

The error trace
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.8/http/client.py", line 1347, in getresponse
    response.begin()
  File "/usr/lib/python3.8/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.8/http/client.py", line 276, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.8/dist-packages/urllib3/util/retry.py", line 532, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.8/dist-packages/urllib3/packages/six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.8/http/client.py", line 1347, in getresponse
    response.begin()
  File "/usr/lib/python3.8/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.8/http/client.py", line 276, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "db_setup.py", line 71, in <module>
    sys_db.create_user(username=u, password=pwd)
  File "/usr/local/lib/python3.8/dist-packages/arango/database.py", line 1748, in create_user
    return self._execute(request, response_handler)
  File "/usr/local/lib/python3.8/dist-packages/arango/api.py", line 74, in _execute
    return self._executor.execute(request, response_handler)
  File "/usr/local/lib/python3.8/dist-packages/arango/executor.py", line 64, in execute
    resp = self._conn.send_request(request)
  File "/usr/local/lib/python3.8/dist-packages/arango/connection.py", line 230, in send_request
    resp = self._http.send_request(
  File "/usr/local/lib/python3.8/dist-packages/arango/http.py", line 124, in send_request
    response = session.request(
  File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
```

**Comment by joowani** [comment]
Hi @lxr900,

My apologies in the delay in getting back you. Have you found out more about this issue? Do you see anything in ArangoDB logs? Thanks.
