### ISSUE TITLE
add_geo_index() fails, does not support geo_json attribute

### ISSUE THREAD

**Issue by velvia** [joowani/python-arango#167]
Calling add_geo_index() does not seem to work for me.  Also, there is no attribute for geo_json in the method, which might be part of the problem.

ArangoDB:  `ArangoDB 3.7.11 [darwin] 64bit, using build , VPack 0.1.33, RocksDB 6.8.0, ICU 64.2, V8 7.9.317, OpenSSL 1.1.1k  25 Mar 2021`
python-arango: 7.1.0.

```
>>> c.add_geo_index("geom", geo_json = True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: add_geo_index() got an unexpected keyword argument 'geo_json'
>>> c.add_geo_index("geom", name = "sj_health_geo")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/evan/.pyenv/versions/ds-utils/lib/python3.7/site-packages/arango/collection.py", line 1203, in add_geo_index
    return self._add_index(data)
  File "/Users/evan/.pyenv/versions/ds-utils/lib/python3.7/site-packages/arango/collection.py", line 1080, in _add_index
    return self._execute(request, response_handler)
  File "/Users/evan/.pyenv/versions/ds-utils/lib/python3.7/site-packages/arango/api.py", line 74, in _execute
    return self._executor.execute(request, response_handler)
  File "/Users/evan/.pyenv/versions/ds-utils/lib/python3.7/site-packages/arango/executor.py", line 65, in execute
    return response_handler(resp)
  File "/Users/evan/.pyenv/versions/ds-utils/lib/python3.7/site-packages/arango/collection.py", line 1077, in response_handler
    raise IndexCreateError(resp, request)
arango.exceptions.IndexCreateError: [HTTP 400][ERR 10] invalid number of index attributes
```

**Comment by joowani** [comment]
Hi @velvia,

Yea I believe that field is indeed missing. I'll look to adding it in the next release. Thanks.

**Comment by velvia** [comment]
Awesome thanks.  Also, which is the bigger development repo going forward, this one, the one in the Arango-community site, or PyArango?

**Comment by joowani** [comment]
Python-arango has had more features and higher API coverage for a while but I haven't been keeping up with PyArango so I cannot say for certain. It might be best to ask the question in ArangoDB slack channels. As for Arango-community vs. this one, I would say this one for now. We're in the transition of moving python-arango to Arango-community (hence the fork) but it hasn't officially taken place yet.
