### ISSUE TITLE
connect to https server

### ISSUE THREAD

**Issue by cer1969** [joowani/python-arango#19]
I have arangodb running on ssl protected server. Admin interface is running ok.

When I try to connect using:

```
client = ArangoClient(protocol="https", host="www.test.com", port=12345, 
    username="root", password="password", enable_logging=True, verify=True
)
```

(python 3.5 on windows 7)

I got an SSL error:
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)

complete traceback:

```
Traceback (most recent call last):
  File "C:\Users\crecheverria\Devel\z_venvs\py64-3.5.1-gen\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 595, in urlopen
    chunked=chunked)
  File "C:\Users\crecheverria\Devel\z_venvs\py64-3.5.1-gen\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 352, in _make_request
    self._validate_conn(conn)
  File "C:\Users\crecheverria\Devel\z_venvs\py64-3.5.1-gen\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 831, in _validate_conn
    conn.connect()
  File "C:\Users\crecheverria\Devel\z_venvs\py64-3.5.1-gen\lib\site-packages\requests\packages\urllib3\connection.py", line 289, in connect
    ssl_version=resolved_ssl_version)
  File "C:\Users\crecheverria\Devel\z_venvs\py64-3.5.1-gen\lib\site-packages\requests\packages\urllib3\util\ssl_.py", line 308, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\Users\crecheverria\Apps\WinPython\64bit-3.5.1.1\python-3.5.1.amd64\lib\ssl.py", line 376, in wrap_socket
    _context=self)
  File "C:\Users\crecheverria\Apps\WinPython\64bit-3.5.1.1\python-3.5.1.amd64\lib\ssl.py", line 747, in __init__
    self.do_handshake()
  File "C:\Users\crecheverria\Apps\WinPython\64bit-3.5.1.1\python-3.5.1.amd64\lib\ssl.py", line 983, in do_handshake
    self._sslobj.do_handshake()
  File "C:\Users\crecheverria\Apps\WinPython\64bit-3.5.1.1\python-3.5.1.amd64\lib\ssl.py", line 628, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Users\crecheverria\Devel\z_venvs\py64-3.5.1-gen\lib\site-packages\requests\adapters.py", line 423, in send
    timeout=timeout
  File "C:\Users\crecheverria\Devel\z_venvs\py64-3.5.1-gen\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 621, in urlopen
    raise SSLError(e)
requests.packages.urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "c:\Users\crecheverria\Devel\SGOT\fallas\v_python\arangodb3\test_02.py", line 16, in <module>
    username="root", password="calipso01", enable_logging=True, verify=True
  File "C:\Users\crecheverria\Devel\z_venvs\py64-3.5.1-gen\lib\site-packages\arango\client.py", line 65, in __init__
    self.verify()
  File "C:\Users\crecheverria\Devel\z_venvs\py64-3.5.1-gen\lib\site-packages\arango\client.py", line 78, in verify
    res = self._conn.head('/_api/version')
  File "C:\Users\crecheverria\Devel\z_venvs\py64-3.5.1-gen\lib\site-packages\arango\connection.py", line 162, in head
    auth=(self._username, self._password)
  File "C:\Users\crecheverria\Devel\z_venvs\py64-3.5.1-gen\lib\site-packages\arango\http_clients\default.py", line 40, in head
    auth=auth
  File "C:\Users\crecheverria\Devel\z_venvs\py64-3.5.1-gen\lib\site-packages\requests\sessions.py", line 510, in head
    return self.request('HEAD', url, **kwargs)
  File "C:\Users\crecheverria\Devel\z_venvs\py64-3.5.1-gen\lib\site-packages\requests\sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\crecheverria\Devel\z_venvs\py64-3.5.1-gen\lib\site-packages\requests\sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\crecheverria\Devel\z_venvs\py64-3.5.1-gen\lib\site-packages\requests\adapters.py", line 497, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)

```

**Comment by joowani** [comment]
Hi cer1969,

It looks like your server does not have a valid SSL certificate.
I release python-arango 3.3.0, which now has a new argument you can use to disable to SSL verification:

```python
client = ArangoClient(
protocol="https", host="www.test.com", port=12345, 
    username="root", password="password", enable_logging=True, verify=True
)
```

**Comment by cer1969** [comment]
I'am using the web interface and the browser says the certificate is valid. I also checked here  https://www.digicert.com/help/.

**Comment by joowani** [comment]
Hi cer1969, 

It could be that the `requests` library (which python-arango uses under the hood) cannot locate the certificate bundle to verify the the certificate of your server. 

Could you try some of the solutions mentioned in http://stackoverflow.com/questions/10667960/python-requests-throwing-up-sslerror? Please note that the new parameter `check_cert` simply passes whatever value you specify to request library's `verify` parameters.

For example, it is possible that you don't have the certificate bundle installed at all which you could solve by something like: `sudo apt-get install ca-certificates` (ubuntu)

Let me know how that goes.
Thanks.

**Comment by cer1969** [comment]
I tried with check_cert="certificate.file" but I got the same error.
Probably a request,py problem.
When I do check_cert=False I understand the certificate is used but not
verified, so if I know the certificate is ok I can trust the connection is
secure?

2016-09-08 12:03 GMT-03:00 Joohwan Oh <notifications@github.com>:

**Comment by joowani** [comment]
If `verify` if set to `False`, the certificate is not checked at all, which leaves you open to man-in-the-middle attack. You would probably be fine going without this check, but ideally you want to fix the core problem. Have you tried this?

```
pip install certifi
```

**Comment by joowani** [comment]
As this is not a problem with python-arango itself I will close this issue now.
