### ISSUE TITLE
KeyError: u'doCompact' error

### ISSUE THREAD

**Issue by afidegnum** [joowani/python-arango#48]
Hi, @joowani can you please look into this issue? 

whenever i tried to find an edge property, i have the following error popping up. 

```
igraph = mygraph.edge_collection('basicgraph')
igraph.properties()
```

```

Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/home/afidegnum/mystore/local/lib/python2.7/site-packages/arango/api.py", line 22, in wrapped_method
    return conn.handle_request(request, handler)
  File "/home/afidegnum/mystore/local/lib/python2.7/site-packages/arango/connection.py", line 164, in handle_request
    return handler(getattr(self, request.method)(**request.kwargs))
  File "/home/afidegnum/mystore/local/lib/python2.7/site-packages/arango/collections/base.py", line 239, in handler
    'compact': res.body['doCompact'],
KeyError: u'doCompact'
```

**Comment by joowani** [comment]
Hi @afidegnum 

Thanks for the bug report.
I've made a new release with the bug fix: https://github.com/joowani/python-arango/releases/tag/3.10.1.
Please upgrade python-arango to the latest version and try again.

Best,
Joohwan

**Comment by joowani** [comment]
@afidegnum Please let me know if the latest release fixed your issue. Thanks

**Comment by afidegnum** [comment]
ok, thanks, i will be checking

**Comment by joowani** [comment]
Hi @afidegnum. 

Haven't heard back from you but the error should've been fixed so I'm closing this one out. Feel free to reopen if you face any more problems.

Thanks,
Joohwan
