### ISSUE TITLE
setup.py fail. import module client in __init__.py cause missing requests dependency

### ISSUE THREAD

**Issue by fmarmol** [joowani/python-arango#74]
After a clone from master.

```
root@4701b129f536:/python-arango# git branch -v
* master d04f3db Revamp the library for 4.0.0.
```

executing  :

```
python setup.py -h

```
produce:

```
root@4701b129f536:/python-arango# python setup.py -h
Traceback (most recent call last):
  File "setup.py", line 3, in <module>
    from arango import version
  File "/python-arango/arango/__init__.py", line 1, in <module>
    from arango.client import ArangoClient  # noqa: F401
  File "/python-arango/arango/client.py", line 5, in <module>
    from arango.connection import Connection
  File "/python-arango/arango/connection.py", line 3, in <module>
    from arango.http import DefaultHTTPClient
  File "/python-arango/arango/http.py", line 7, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
```

**Comment by joowani** [comment]
Hi @fmarmol,

Thank you for the bug report! The issue should be fixed in version [4.0.1](https://github.com/joowani/python-arango/releases/tag/4.0.1) just released. Please feel free to re-open if you still see any issues.
